name: percent_indicator
description: A new flutter package project.
version: 1.0.0
author: diegoveloper
homepage: https://github.com/diegoveloper/flutter_percent_indicator/

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: